import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { Plus, Minus, ShoppingBag } from 'lucide-react';
import { toast } from 'sonner';
import { useStore } from '@/components/store';
import { products, pageHead, money, effectivePrice, sizeStock } from '@/lib/catalog';
import { validateDiscount, setPendingPromo } from '@/lib/discounts';
import { Button } from '@/components/ui/button';
export const Route=createFileRoute('/cart')({head:()=>pageHead('Your Shopping Bag','Review your HUDA GYMWEAR pieces, adjust quantities and preview checkout.'),component:Cart});
function Cart(){const {bag,change,toggleWish,wishlist}=useStore();const [code,setCode]=useState('');const [saved,setSaved]=useState(0);const total=bag.reduce((n,i)=>{const p=products.find(p=>p.id===i.id);return n+(p?effectivePrice(p):0)*i.quantity;},0);return <><div className="page-header"><span className="eyebrow">YOUR NEXT FAVOURITE FIT</span><h1>Your Bag</h1><p>{bag.reduce((n,i)=>n+i.quantity,0)} pieces. All you.</p></div>{!bag.length?<div className="empty-state"><ShoppingBag size={36}/><h2>Something good is missing.</h2><Button variant="fashion" asChild><Link to="/shop">EXPLORE THE COLLECTION</Link></Button></div>:<div className="cart-layout"><div>{bag.map(i=>{const p=products.find(p=>p.id===i.id);if(!p)return null;return <div className="bag-row" key={i.id+i.size}><Link to="/product/$id" params={{id:i.id}}><img src={p.image} alt={p.name} width={96} height={144}/></Link><div><h3>{p.name}</h3><p>{p.colour} / {i.size}</p><strong>{p.salePrice?<><del>{money(p.price)} </del>{money(p.salePrice)}</>:money(p.price)}</strong><div className="quantity"><Button variant="tool" aria-label={`Decrease ${p.name}`} onClick={()=>change(i.id,i.size,-1)}><Minus/></Button><span>{i.quantity}</span><Button variant="tool" aria-label={`Increase ${p.name}`} disabled={i.quantity>=sizeStock(p,i.size)} title={i.quantity>=sizeStock(p,i.size)?'No more left in this size':`Increase ${p.name}`} onClick={()=>change(i.id,i.size,1)}><Plus/></Button></div><div className="cart-actions"><Button variant="link" size="sm" onClick={()=>change(i.id,i.size,-i.quantity)}>Remove</Button><Button variant="link" size="sm" onClick={()=>{if(!wishlist.includes(i.id))toggleWish(i.id);change(i.id,i.size,-i.quantity);toast.success('Saved to your wishlist')}}>Save for later</Button></div></div></div>})}</div><div className="checkout-summary"><h2>Your summary</h2><div className="bag-total"><span>Subtotal</span><strong>{money(total)}</strong></div><div className="bag-total"><span>Delivery</span><span>Confirmed at launch</span></div><form className="promo-form" onSubmit={e=>{e.preventDefault();const r=validateDiscount(code,total);if(r.ok){setSaved(r.amount);setPendingPromo(code);toast.success(`${code.trim().toUpperCase()} applied — carried to checkout, you save ${money(r.amount)}.`);}else{setSaved(0);setPendingPromo('');toast.error(r.message);}}}><input value={code} onChange={e=>{setCode(e.target.value);setSaved(0);setPendingPromo('');}} required aria-label="Promo code" placeholder="Promo code"/><Button variant="quiet" type="submit">Apply</Button></form>{saved>0&&<div className="bag-total discount"><span>Estimated savings</span><strong>−{money(saved)}</strong></div>}<div className="bag-total"><strong>Total before delivery</strong><strong>{money(Math.max(0,total-saved))}</strong></div><Button variant="fashion" className="w-full mt-6" asChild><Link to="/checkout">CONTINUE TO CHECKOUT</Link></Button><p className="fine-print">Fast UK dispatch · 28-day effortless returns</p></div></div>}</>}
