import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ProductCard } from '@/components/store';
import { pageHead, activeProducts } from '@/lib/catalog';
import { homepageFavourites, formCards } from '@/lib/merch';
import heroImg from '@/assets/hero.png';
import campaign from '@/assets/campaign.png';
export const Route=createFileRoute('/')({head:()=>pageHead('Premium Women’s Activewear','Luxury-inspired activewear for every version of you. Discover leggings, sports bras and matching sets from HUDA GYMWEAR.',{path:'/'}),component:Index});
function Index(){return <><section className="hero"><img src={heroImg} alt="HUDA GYMWEAR black performance activewear campaign" width={1920} height={1024} fetchPriority="high"/><div className="hero-content"><span className="eyebrow">THE EVERYDAY, ELEVATED.</span><h1>YOUR STRENGTH.<br/>YOUR STYLE.</h1><p>Performance meets confidence.<br/>Premium activewear for every version of you.</p><Button variant="fashion" asChild><Link to="/shop">SHOP THE COLLECTION <ArrowRight/></Link></Button></div><div className="hero-bottom"><span>MOVE WITH PURPOSE. WEAR WITH CONFIDENCE.</span><span className="hero-position">01 / 01</span></div></section><div className="brand-ribbon"><span>SCULPTING FITS</span><span className="ribbon-dot">◆</span><span>SECOND-SKIN COMFORT</span><span className="ribbon-dot">◆</span><span>EFFORTLESS STYLE</span><span className="ribbon-dot">◆</span><span>UNCOMPROMISING YOU</span></div><section className="section"><div className="section-heading"><div><span className="eyebrow">YOUR NEW EVERYDAY ESSENTIALS</span><h2>The favourites. For a reason.</h2></div><Link to="/shop" className="text-link">SHOP ALL <ArrowRight size={14}/></Link></div><div className="product-grid">{homepageFavourites(activeProducts()).map(p=><ProductCard key={p.id} product={p}/>)}</div></section><section className="section category-section"><div className="section-heading"><div><span className="eyebrow">FIND YOUR FORM</span><h2>Made for your kind of movement.</h2></div></div><div className="category-grid">{formCards(activeProducts()).map(c=><Link to="/shop" search={{category:c.name}} className="category-card" key={c.name}><img src={c.image} loading="lazy" width={768} height={1152} alt={c.name}/><span className="category-caption">{c.name}<ArrowRight size={19}/></span></Link>)}</div></section><section className="story-band"><img src={campaign} loading="lazy" alt="Strength and elegance in motion" width={1717} height={916}/><div className="story-content"><span className="eyebrow">MORE THAN WHAT YOU WEAR</span><h2>Confidence looks<br/>good on you.</h2><p>For early starts. For new personal bests. For the days you show up for yourself. We create activewear that feels as strong as you are.</p><Link to="/about" className="text-link">THE HUDA STORY <ArrowRight size={16}/></Link></div></section><section className="community"><span className="eyebrow">STRONGER, TOGETHER.</span><h2>A movement of our own.</h2><p>Different journeys. One shared confidence. #HUDAGYMWEAR</p></section></>}
