/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BestSellersRouteImport } from './routes/best-sellers'
import { Route as BottomsRouteImport } from './routes/bottoms'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HoodiesRouteImport } from './routes/hoodies'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LeggingsRouteImport } from './routes/leggings'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as SetsRouteImport } from './routes/sets'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as SportsBrasRouteImport } from './routes/sports-bras'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TopsRouteImport } from './routes/tops'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccountResetRouteImport } from './routes/account.reset'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as CollectionsHandleRouteImport } from './routes/collections/$handle'
import { Route as ProductIdRouteImport } from './routes/product/$id'
import { Route as AdminOrdersNewRouteImport } from './routes/admin/orders.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellersRoute = BestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const BottomsRoute = BottomsRouteImport.update({
  id: '/bottoms',
  path: '/bottoms',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HoodiesRoute = HoodiesRouteImport.update({
  id: '/hoodies',
  path: '/hoodies',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LeggingsRoute = LeggingsRouteImport.update({
  id: '/leggings',
  path: '/leggings',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsRoute = SetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsBrasRoute = SportsBrasRouteImport.update({
  id: '/sports-bras',
  path: '/sports-bras',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TopsRoute = TopsRouteImport.update({
  id: '/tops',
  path: '/tops',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetRoute = AccountResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/admin/discounts',
  path: '/admin/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/account': typeof AccountRouteWithChildren
  '/best-sellers': typeof BestSellersRoute
  '/bottoms': typeof BottomsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/hoodies': typeof HoodiesRoute
  '/launch': typeof LaunchRoute
  '/leggings': typeof LeggingsRoute
  '/lookbook': typeof LookbookRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sets': typeof SetsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/sports-bras': typeof SportsBrasRoute
  '/terms': typeof TermsRoute
  '/tops': typeof TopsRoute
  '/wishlist': typeof WishlistRoute
  '/account/reset': typeof AccountResetRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/account': typeof AccountRouteWithChildren
  '/best-sellers': typeof BestSellersRoute
  '/bottoms': typeof BottomsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/hoodies': typeof HoodiesRoute
  '/launch': typeof LaunchRoute
  '/leggings': typeof LeggingsRoute
  '/lookbook': typeof LookbookRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sets': typeof SetsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/sports-bras': typeof SportsBrasRoute
  '/terms': typeof TermsRoute
  '/tops': typeof TopsRoute
  '/wishlist': typeof WishlistRoute
  '/account/reset': typeof AccountResetRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/account': typeof AccountRouteWithChildren
  '/best-sellers': typeof BestSellersRoute
  '/bottoms': typeof BottomsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/hoodies': typeof HoodiesRoute
  '/launch': typeof LaunchRoute
  '/leggings': typeof LeggingsRoute
  '/lookbook': typeof LookbookRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sets': typeof SetsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/sports-bras': typeof SportsBrasRoute
  '/terms': typeof TermsRoute
  '/tops': typeof TopsRoute
  '/wishlist': typeof WishlistRoute
  '/account/reset': typeof AccountResetRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessories'
    | '/account'
    | '/best-sellers'
    | '/bottoms'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/help'
    | '/hoodies'
    | '/launch'
    | '/leggings'
    | '/lookbook'
    | '/new-arrivals'
    | '/order-success'
    | '/orders'
    | '/privacy'
    | '/returns'
    | '/sets'
    | '/shipping'
    | '/shop'
    | '/size-guide'
    | '/sports-bras'
    | '/terms'
    | '/tops'
    | '/wishlist'
    | '/account/reset'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/collections/$handle'
    | '/product/$id'
    | '/admin/'
    | '/admin/orders/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessories'
    | '/account'
    | '/best-sellers'
    | '/bottoms'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/help'
    | '/hoodies'
    | '/launch'
    | '/leggings'
    | '/lookbook'
    | '/new-arrivals'
    | '/order-success'
    | '/orders'
    | '/privacy'
    | '/returns'
    | '/sets'
    | '/shipping'
    | '/shop'
    | '/size-guide'
    | '/sports-bras'
    | '/terms'
    | '/tops'
    | '/wishlist'
    | '/account/reset'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/collections/$handle'
    | '/product/$id'
    | '/admin'
    | '/admin/orders/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessories'
    | '/account'
    | '/best-sellers'
    | '/bottoms'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/help'
    | '/hoodies'
    | '/launch'
    | '/leggings'
    | '/lookbook'
    | '/new-arrivals'
    | '/order-success'
    | '/orders'
    | '/privacy'
    | '/returns'
    | '/sets'
    | '/shipping'
    | '/shop'
    | '/size-guide'
    | '/sports-bras'
    | '/terms'
    | '/tops'
    | '/wishlist'
    | '/account/reset'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/collections/$handle'
    | '/product/$id'
    | '/admin/'
    | '/admin/orders/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AccountRoute: typeof AccountRouteWithChildren
  BestSellersRoute: typeof BestSellersRoute
  BottomsRoute: typeof BottomsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  HoodiesRoute: typeof HoodiesRoute
  LaunchRoute: typeof LaunchRoute
  LeggingsRoute: typeof LeggingsRoute
  LookbookRoute: typeof LookbookRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  SetsRoute: typeof SetsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  SizeGuideRoute: typeof SizeGuideRoute
  SportsBrasRoute: typeof SportsBrasRoute
  TermsRoute: typeof TermsRoute
  TopsRoute: typeof TopsRoute
  WishlistRoute: typeof WishlistRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  ProductIdRoute: typeof ProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-sellers': {
      id: '/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof BestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bottoms': {
      id: '/bottoms'
      path: '/bottoms'
      fullPath: '/bottoms'
      preLoaderRoute: typeof BottomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoodies': {
      id: '/hoodies'
      path: '/hoodies'
      fullPath: '/hoodies'
      preLoaderRoute: typeof HoodiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leggings': {
      id: '/leggings'
      path: '/leggings'
      fullPath: '/leggings'
      preLoaderRoute: typeof LeggingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets': {
      id: '/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof SetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-bras': {
      id: '/sports-bras'
      path: '/sports-bras'
      fullPath: '/sports-bras'
      preLoaderRoute: typeof SportsBrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tops': {
      id: '/tops'
      path: '/tops'
      fullPath: '/tops'
      preLoaderRoute: typeof TopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset': {
      id: '/account/reset'
      path: '/reset'
      fullPath: '/account/reset'
      preLoaderRoute: typeof AccountResetRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/admin/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/new': {
      id: '/admin/orders/new'
      path: '/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AccountRouteChildren {
  AccountResetRoute: typeof AccountResetRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountResetRoute: AccountResetRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminOrdersRouteChildren {
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersNewRoute: AdminOrdersNewRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRoute,
  AccountRoute: AccountRouteWithChildren,
  BestSellersRoute: BestSellersRoute,
  BottomsRoute: BottomsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  HoodiesRoute: HoodiesRoute,
  LaunchRoute: LaunchRoute,
  LeggingsRoute: LeggingsRoute,
  LookbookRoute: LookbookRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  SetsRoute: SetsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  SizeGuideRoute: SizeGuideRoute,
  SportsBrasRoute: SportsBrasRoute,
  TermsRoute: TermsRoute,
  TopsRoute: TopsRoute,
  WishlistRoute: WishlistRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  ProductIdRoute: ProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
